const fs = require('fs');
const path = require('path');

const DIST_DIR = 'dist';
const SRC_DIR = 'src';
const OUTPUT_FILE = path.join(SRC_DIR, 'flexible-weather-card.js');

// Ensure src dir exists
if (!fs.existsSync(SRC_DIR)) {
    fs.mkdirSync(SRC_DIR);
}

// 1. Read Editor File
console.log('Processing editor...');
let editorContent = fs.readFileSync(path.join(DIST_DIR, 'flexible-weather-card-editor.js'), 'utf8');

// Remove duplicate LitElement/html/css declarations from editor
// (these are already defined in the main file)
editorContent = editorContent.replace(
    /const LitElement = customElements\.get\("ha-lit-element"\).*;\s*const html = LitElement\.prototype\.html;\s*const css = LitElement\.prototype\.css;\s*/,
    ''
);

// 2. Read Main Card File
console.log('Processing main card...');
let mainContent = fs.readFileSync(path.join(DIST_DIR, 'flexible-weather-card.js'), 'utf8');

// 3. Combine everything
console.log('Writing output...');
const finalContent = `/**
 * Flexible Weather Card (Bundled)
 * Generated by build.js
 * Source: dist/flexible-weather-card.js + dist/flexible-weather-card-editor.js
 */

${mainContent}

${editorContent}
`;

fs.writeFileSync(OUTPUT_FILE, finalContent);
console.log(`Build complete: ${OUTPUT_FILE}`);
